/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-leon-uart.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccContext_leon_uart_Initialize(asn1SccContext_leon_uart* pVal)
{
    *pVal = (asn1SccContext_leon_uart) {
    .driver_configuration = {
        .console_id = 0,
        .baud = 0
    }
};
}
#endif

 
flag asn1SccContext_leon_uart_IsConstraintValid(const asn1SccContext_leon_uart* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccLEON_UART_Configuration_IsConstraintValid(&pVal->driver_configuration, pErrCode);


	return ret;
}

const asn1SccContext_leon_uart leon_uart_ctxt = {
    .driver_configuration = {
        .console_id = 1,
        .baud = 19200
    }
};
