/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-systeminit.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccContext_systeminit_Initialize(asn1SccContext_systeminit* pVal)
{
    *pVal = (asn1SccContext_systeminit) {
    .console_configuration = {
        .console_id = 0,
        .baud = 0
    }
};
}
#endif

 
flag asn1SccContext_systeminit_IsConstraintValid(const asn1SccContext_systeminit* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccLEON_UART_Configuration_IsConstraintValid(&pVal->console_configuration, pErrCode);


	return ret;
}

const asn1SccContext_systeminit systeminit_ctxt = {
    .console_configuration = {
        .console_id = 0,
        .baud = 115200
    }
};
