#ifndef GENERATED_ASN1SCC_CONTEXT_SYSTEMINIT_H
#define GENERATED_ASN1SCC_CONTEXT_SYSTEMINIT_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccLEON_UART_Configuration console_configuration;
} asn1SccContext_systeminit;

#define asn1SccContext_systeminit_REQUIRED_BYTES_FOR_ENCODING       3 
#define asn1SccContext_systeminit_REQUIRED_BITS_FOR_ENCODING        24
#define asn1SccContext_systeminit_REQUIRED_BYTES_FOR_ACN_ENCODING   3 
#define asn1SccContext_systeminit_REQUIRED_BITS_FOR_ACN_ENCODING    24
#define asn1SccContext_systeminit_REQUIRED_BYTES_FOR_XER_ENCODING   166

void asn1SccContext_systeminit_Initialize(asn1SccContext_systeminit* pVal);
flag asn1SccContext_systeminit_IsConstraintValid(const asn1SccContext_systeminit* val, int* pErrCode);


extern const asn1SccContext_systeminit systeminit_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
